Rails.application.routes.draw do
  get 'attendall/pre6/:id', to:'attends#attendall_pre6'
  get 'attendall/pre5/:id', to:'attends#attendall_pre5'
  get 'attendall/pre4/:id', to:'attends#attendall_pre4'
  get 'attendall/pre3/:id', to:'attends#attendall_pre3'
  get 'attendall/pre2/:id', to:'attends#attendall_pre2'
  get 'attendall/pre1/:id', to:'attends#attendall_pre1'
  get 'attendall/:id', to:'attends#attendall'
  get 'attendall/next1/:id', to:'attends#attendall_next1'
  get 'attendall/next2/:id', to:'attends#attendall_next2'
  get 'attendall/next3/:id', to:'attends#attendall_next3'
  get 'attendall/next4/:id', to:'attends#attendall_next4'
  get 'attendall/next5/:id', to:'attends#attendall_next5'
  get 'attendall/next6/:id', to:'attends#attendall_next6'
  get 'attend/edit/:id', to:'attends#edit_attend'
  post 'attend/regist/:id', to:'attends#regist_attend'
  post 'destroy/remark/:id', to:'attends#destroy_remark'
  get 'attend/index', to:'attends#index_attend'
  get 'confirm/paidholi/:id', to:'attends#paidholipage'
  
  get 'jobs/show/:id', to:'jobs#show_job'
  get 'jobs/new', to:'jobs#new_job'
  post 'work', to:'jobs#create_job'
  get 'index/:id', to:'jobs#index_job'
  get 'jobs/index', to:'jobs#index_all'
  
  get 'mypage', to:'users#mypage'
  post 'clockon', to:'users#clockon'
  post 'clockout', to:'users#clockout'
  post 'attend/destroy/:id', to:'users#destroy_attend'
  post 'remark', to:'users#remark'
  get 'index', to:'users#index'
  get 'show/:id', to:'users#show'
  post 'paidholi/:id', to:'users#paidholi'
  post 'paidholi/10/:id', to:'users#paidholi_plusten'
  get 'edit', to:'users#edit'
  post 'update', to:'users#update'
  get 'depa/edit/:id', to:'users#edit_depa'
  post 'depa/update/:id', to:'users#update_depa'
  post 'destroy/:id', to: 'users#destroy'
  get 'signup', to:'users#new'
  post 'create', to: 'users#create'
  get 'login', to: 'users#login_form'
  post 'login', to: 'users#login'
  post 'logout', to: 'users#logout'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
